dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    version: "0.6.6"    # version of solc to use
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env

networks:
  sepolia:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  ganache-local1:
    verify: False
  development:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
